create database customer_shopping_behavior;

select * from customer;

desc customer;

-- What is the total revenue generated by each product category?
select category, sum(purchase_amount_usd) as total
from customer
group by category
order by total desc;

-- Which product category have the highest avg purchase amount?
select category, avg(purchase_amount_usd) as avg_total
from customer
group by category
order by avg_total desc; 

-- Which location generate the most revenue?
select location, sum(purchase_amount_usd) as total
from customer
group by location
order by total desc; 

-- Which groups spend the most?
select age_group, count(*) as total_purchases, avg(purchase_amount_usd) as avg_total, sum(purchase_amount_usd) as total
from customer
group by age_group
order by total desc;

-- payment method most commonly used by customers
select payment_method, count(*) as total_purchases
from customer
group by payment_method
order by total_purchases desc;


-- products having highest number of purchases
select item_purchased, count(*) as total_purchases
from customer
group by item_purchased
order by total_purchases desc;

-- Which shipping type is preferred by customers?
select shipping_type, count(*) as total_orders
from customer
group by shipping_type
order by total_orders desc;